# Generated by Django 4.0.5 on 2022-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='author_avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
