# Generated by Django 4.0.5 on 2022-06-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_rename_user_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='gallery_avatar',
        ),
        migrations.AddField(
            model_name='photogallery',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
