# Generated by Django 4.0.5 on 2022-06-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_remove_photogallery_gallery_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='photo_gallery',
        ),
        migrations.DeleteModel(
            name='WebsiteCover',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
