# Generated by Django 4.0.5 on 2022-06-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cover', models.ImageField(upload_to='CoursesCover/%Y/%m/%d')),
                ('video_course', models.FileField(upload_to='VideoCourse/certificate/%Y/%m/%d')),
                ('draft', models.BooleanField(default=False)),
            ],
        ),
    ]
