# Generated by Django 4.0.5 on 2022-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
