# Generated by Django 4.0.5 on 2022-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
