# Generated by Django 4.0.5 on 2022-06-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_anonymousformorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousFormOrders',
        ),
    ]
