# Generated by Django 4.0.5 on 2022-06-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0004_remove_comment_author_remove_comment_photo_gallery_and_more'),
        ('courses', '0001_initial'),
        ('orders', '0007_alter_orders_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousFormOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_gallery.photogallery')),
            ],
        ),
    ]
